spring:
  datasource:
    url: jdbc:mysql://10.122.2.78:6033/plancenter?characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: plancenter
    password: Yuantu123
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.smj.testboot.bean
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl